// <auto-generated />
namespace AlexBeeBookRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DbSetUpBookAndGenreCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbSetUpBookAndGenreCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201808301222510_DbSetUpBookAndGenreCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
